[package]
name = "rola"
version = "0.0.1"
authors = ["mikopits <mikopits@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/mikopits/rola"

[dependencies]
num = "0.1"
ocl = "0.13"
libc = "^0.1.8"
